### ISSUE TITLE
Can't install plugin in Gitlab CI with alpine/helm image

### ISSUE THREAD

**Issue by MoskitoHero** [datreeio/helm-datree#22]
**Describe the bug**
When trying to install the plugin in Gitlab CI with the alpine/helm, I get a failure.

**To Reproduce**
1. Run this script in Gitlab CI (truncated for privacy reasons)
```yaml
stages:
  - test

test:
  stage: test
  image:
    name: alpine/helm:3.7.2
    entrypoint: [""]
  variables:
    DATREE_TOKEN: XXXXXXXXXXXXXXXXXXXXX
    HELM_PLUGINS: ./.helm_plugins
  before_script:
    # Debugging pluging
    - helm plugin list # Should be empty
    # Install another plugin just to check
    - helm plugin install https://github.com/technosophos/helm-github
    - helm plugin list # Should list the helm-github plugin
    - helm plugin install https://github.com/datreeio/helm-datree
    - helm plugin list # Should list both pluging
  script:
    - ...

```

2. See error `sh: ./scripts/install.sh: not found`

![image](https://user-images.githubusercontent.com/346985/146383810-a4ed7005-6d94-4bb2-a091-dd60962087d5.png)

**Expected behavior**
The plugin should install

**Datree plugin version (run `helm datree verion`):**
 - Version: probably the latest at the time of writing.
